### ISSUE TITLE
Occasional single-frame flickers of gui/text in the wrong position

### ISSUE THREAD

**Issue by seleb** [lunafromthemoon/RenJS-V2#32] opened 2021-10-30 08:34 UTC
I'm not exactly sure what triggers this, but it seems that in a variety of cases, text and/or images will be rendered in the top-left corner for a single frame before being placed in the expected position. A few of the cases I saw this happening:

- The character name when there's a change in who's speaking (this one seemed to repro pretty consistently and is probably easiest to debug)
- Credits text when the credits roll starts
- Title/loader bg when first starting the game

**Comment by lunafromthemoon** [comment] 2021-10-30 08:40
For the text issues, i've tried to debug this with Phaser and got nowhere, the problem is that when you change the text property of a text object there is a delay when showing, but you don't get any handle to know when the text is actually ready. I was thinking the best way could directly be destroying the text object and recreate it everytime you show, for example, the namebox.

**Comment by lunafromthemoon** [comment] 2021-11-01 18:44
The issue seems to be solved for most cases (at least from what I could find), let me know if we can close this.

**Comment by seleb** [comment] 2021-11-01 18:52
I think it's safe to close, yeah! The specific cases listed are fixed and I haven't seen any more, so it'd prob be best to just open a new issue if others are found.

**Closed** 2021-11-01 18:55 UTC
